name: Calendar Workflow

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  calendar-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Files
        run: ls -la

      - name: Show Python Version
        run: python --version

      - name: Syntax Check
        run: python -m py_compile displayCalendar.py

      - name: Run Calendar Program
        run: |
          echo -e "2026\n5" | python calendar_app.py

      - name: Done
        run: echo "Workflow completed successfully"
